font_family      JetBrains Maple Mono
bold_font        Maple Mono NF Bold
italic_font      Maple Mono NF Italic
bold_italic_font Maple Mono NF Medium Italic
font_size        11.5

modify_font cell_height 122%

background_opacity         0.7
background_blur            32
dynamic_background_opacity yes

cursor            #ff0055
cursor_text_color #24273a
cursor_trail      1
cursor_trail_decay 0.1 0.2
cursor_blink_interval 0

hide_window_decorations yes
# tab_bar_style        powerline
# tab_powerline_style  slanted
# tab_title_template   "{f'{title[:30]}…' if title.rindex(title[-1]) + 1 > 30 else (title.center(6) if (title.rindex(title[-1]) + 1) % 2 == 0 else title.center(5))}"

active_tab_foreground   #181926
active_tab_background   #b7bdf8
inactive_tab_foreground #cad3f5
inactive_tab_background #1e2030
tab_bar_background      #181926

foreground #ffffff
selection_foreground #24273a
selection_background #f4dbd6
url_color #f4dbd6

# Tokyo Night / Catppuccin Hybrid Colors
color0 #15161e
color1 #f7768e
color2 #9ece6a
color3 #e0af68
color4 #7aa2f7
color5 #bb9af7
color6 #7dcfff
color7 #a9b1d6
color8 #5b6078
color9 #ed8796
color10 #a6da95
color11 #eed49f
color12 #8aadf4
color13 #f5bde6
color14 #8bd5ca
color15 #a5adcb

confirm_os_window_close 0
